import type { Metadata } from "next";
import "./globals.css";
import Navbar from './components/navbar';

export const metadata: Metadata = {
  title: "travaling life",
  description: "Generated by create next app",
   icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <Navbar />
        <main className="flex-grow pt-16">
          {children}
        </main>
      </body>
    </html>
  );
}